# GET http://localhost:8888/.netlify/functions/faunaTest

# GET http://localhost:8888/.netlify/functions/functionsPing

# GET http://localhost:8888/.netlify/functions/echoContext

# GET http://localhost:8888/.netlify/functions/hello
# GET http://localhost:8888/.netlify/functions/initializeTranscriptionAWS


# GET https://322a-174-248-207-172.ngrok.io/.netlify/functions/hello

# POST http://322a-174-248-207-172.ngrok.io/.netlify/functions/completedTranscriptionCallback

GET http://localhost:8888/.netlify/functions/fetchUserRecordings 

# POST https://boring-varahamihira-cc7a90.netlify.app/.netlify/functions/fetchUserRecordings HTTP/1.1
# {
#     "after": {
#       "body" : {
#         "after" : []
#       }
#     },
#     "context" : {
#       "clientContext" : {
#         "user" : {
#           "id" : "cb27daef-4bfc-4f69-9d44-113e4605bad2"
#         }
#       }
#     }
# }