type User {
  netlifyID: ID! # ! means can't return null
  email: String!
  name: String
  recordings: [Recording!] @relation
}

type Recording {
  title: String
  date: Time
  original: RecordingURL! @relation
  transcoded: RecordingURL @relation
  low_fi: RecordingURL
  transloadit: String # Archive of transloadit payload
  user: User!
}

type RecordingURL {
  url: String!
  ssl_url: String
}
